spring.application.name=eclappse
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_eclappse;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
